onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_wishbone/simdone
add wave -noupdate /tb_top_wishbone/Clk
add wave -noupdate /tb_top_wishbone/Rst
add wave -noupdate /tb_top_wishbone/TimeoutAck_Detected
add wave -noupdate /tb_top_wishbone/TimeoutAck_Rec_Clear
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_wishbone/executing_line
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_wishbone/executing_file
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_wishbone/marker
add wave -noupdate /tb_top_wishbone/signals_in
add wave -noupdate /tb_top_wishbone/signals_out
add wave -noupdate /tb_top_wishbone/bus_down
add wave -noupdate /tb_top_wishbone/bus_up
add wave -noupdate /tb_top_wishbone/SpiControllerIfcWishboneDown
add wave -noupdate /tb_top_wishbone/SpiControllerIfcWishboneUp
add wave -noupdate /tb_top_wishbone/SpiControllerIfcTrace
add wave -noupdate /tb_top_wishbone/SClk
add wave -noupdate /tb_top_wishbone/MiSo
add wave -noupdate /tb_top_wishbone/MoSi
add wave -noupdate /tb_top_wishbone/nCs
add wave -noupdate /tb_top_wishbone/WPn
add wave -noupdate /tb_top_wishbone/HOLDn
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/clk
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/rst
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/simdone
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/executing_line
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/executing_file
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/marker
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/signals_out
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/signals_in
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/bus_down
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/bus_up
add wave -noupdate /tb_top_wishbone/tb_FileIo_i/rstneg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/WishboneDown
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/WishboneUp
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/Trace
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/SpiControllerBlkDown
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/SpiControllerBlkUp
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/BlockMatch
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/UnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/TimeoutAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/PreWishboneUp
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/SpiControllerBlkDatOut
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/SpiControllerBlkAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/SpiControllerBlkMatch
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/Cyc
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/Match
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/UnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/TimeoutAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/CycDelay
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/PreUnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/PreTimeoutAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerIfcBusMonitor/TimeoutCounter
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Adr
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Sel
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/DatIn
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/We
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Stb
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Cyc
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/DatOut
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Ack
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Match
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Activation
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/SwBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/WTransPulseControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/Operation
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/HwBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferAdr
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferSel
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferWe
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferStb
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferDatOut
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferDatIn
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferAck
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/CellBufferCyc
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreDatOut
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreDatOutControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreReadAckControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreWriteAckControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchWriteControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/WriteDiffControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/ReadDiffControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/WRegActivation
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreDatOutStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreReadAckStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreWriteAckStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchWriteStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/WriteDiffStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/ReadDiffStatusReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreDatOutCellBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreAckCellBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadCellBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_SpiControllerIfcWishbone/i_SpiControllerBlk_SpiControllerIfc/PreMatchWriteCellBuffer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/SClk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/MiSo
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/MoSi
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/DoTransceivePulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/ReleaseTxDataPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/StoreRxDataPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/TxByte
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/RxByte
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/CPol
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/CPha
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/SClkPeriodInNs
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/TranceiveCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/StretchCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/TxShiftReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_Phy/RxShiftReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/Activation
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/SwBufferPrepared
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/WTransPulseControlReg
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/Operation
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferAvailable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/SelectedBufferNumberOwnedBySw
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferAddress
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferWriteEnable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferWriteData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferReadData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/CPol
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/CPha
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/SClkPeriodInNs
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/DoTransceivePulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ReleaseTxDataPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/StoreRxDataPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/TxByte
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/RxByte
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/nCs
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/State
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/CmdId
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ReadHwBufferAddressPointer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ReadHwBufferRepeatAddressPointer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/WriteHwBufferAddressPointer
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ReceiveFrameStartAddress
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/PacketMultiplier
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/PacketLength
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/PacketCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ByteCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ReceiveByteCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/StoreReceiveByte
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ResetReceiveByteCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/WaitNs
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/StartTimerPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/TimerCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/TimerExpired
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/CmdGotoAddressToGoto
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/ForLoopCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/LoopCount
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/CmdEndAddressToGoto
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/AutoRestart
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/SwBuffersPending
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/HwBufferProcessedPulse
add wave -noupdate /tb_top_wishbone/i_SpiController/i_CmdProcessor/Tranceive
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/Rst
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/SelectedBufferNumberOwnedBySw
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/HwBufferWriteEnable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/HwBufferAddress
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/HwBufferWriteData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/HwBufferReadData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/SwBufferWriteEnable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/SwBufferAddress
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/SwBufferWriteData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/SwBufferReadData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferWriteEnable0
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferAddress0
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferWriteData0
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferReadData0
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferWriteEnable1
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferAddress1
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferWriteData1
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/BufferReadData1
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/WriteEnable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/Address
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/WriteData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/ReadData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i0_Ram/ReadAddress
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/Clk
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/WriteEnable
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/Address
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/WriteData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/ReadData
add wave -noupdate /tb_top_wishbone/i_SpiController/i_DoubleBuffer/i1_Ram/ReadAddress
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/CSn
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/CLK
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/DIO
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/WPn
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/HOLDn
add wave -noupdate /tb_top_wishbone/i_W25Q128JVxIM/DO
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {247 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 647
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {271024207 ps} {271025042 ps}
