onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_axi4lite/simdone
add wave -noupdate /tb_top_axi4lite/Clk
add wave -noupdate /tb_top_axi4lite/Rst
add wave -noupdate /tb_top_axi4lite/TimeoutAck_Detected
add wave -noupdate /tb_top_axi4lite/TimeoutAck_Rec_Clear
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_axi4lite/executing_line
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_axi4lite/executing_file
add wave -noupdate -color Magenta -itemcolor Magenta /tb_top_axi4lite/marker
add wave -noupdate /tb_top_axi4lite/signals_in
add wave -noupdate /tb_top_axi4lite/signals_out
add wave -noupdate /tb_top_axi4lite/bus_down
add wave -noupdate /tb_top_axi4lite/bus_up
add wave -noupdate /tb_top_axi4lite/SpiControllerIfcAxi4LiteDown
add wave -noupdate /tb_top_axi4lite/SpiControllerIfcAxi4LiteUp
add wave -noupdate /tb_top_axi4lite/SpiControllerIfcTrace
add wave -noupdate /tb_top_axi4lite/SClk
add wave -noupdate /tb_top_axi4lite/MiSo
add wave -noupdate /tb_top_axi4lite/MoSi
add wave -noupdate /tb_top_axi4lite/nCs
add wave -noupdate /tb_top_axi4lite/WPn
add wave -noupdate /tb_top_axi4lite/HOLDn
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/clk
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/rst
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/simdone
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/executing_line
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/executing_file
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/marker
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/signals_out
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/signals_in
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/bus_down
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/bus_up
add wave -noupdate /tb_top_axi4lite/tb_FileIo_i/rstneg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SpiControllerIfcAxi4LiteDown
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SpiControllerIfcAxi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SpiControllerIfcTrace
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SClk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/MiSo
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/MoSi
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/nCs
add wave -noupdate -expand /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SpiControllerBlkDown
add wave -noupdate -expand /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SpiControllerBlkUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SelectedBufferNumberOwnedBySw
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SwBufferWriteEnable
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/HwBufferWriteEnable
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/HwBufferAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/HwBufferWriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/HwBufferReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/DoTransceivePulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/ReleaseTxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/StoreRxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/TxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/CPol
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/CPha
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/SClkPeriodInNs
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/ExtReadAckRamDelay
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RamIfcAxi4LiteDown
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RamIfcAxi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RamIfcTrace
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RamIfcRamBlkDown
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/RamIfcRamBlkUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Axi4LiteDown
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Axi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Axi4LiteAccess
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Trace
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkDown
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/PreAxi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/PreAxi4LiteAccess
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/UnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/TimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Read
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadAddressMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteAddrMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/WriteStrobe
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkWriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkWriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/SpiControllerBlkWriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/AWVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/AWADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/AWPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/AWREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WSTRB
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/BREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/BVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/BRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ARVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ARADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ARPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ARREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/RREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/RVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/RDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/RRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WritePrivileged
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteSecure
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteInstruction
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadPrivileged
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadSecure
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadInstruction
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Read
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadAddressMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteAddrMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteStrobe
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/UnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/TimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Axi4LiteReadState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/Axi4LiteWriteState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadTimeoutCounter
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteTimeoutCounter
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadUnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteUnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadTimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteTimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/ReadProtect
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerIfcAxi4LiteBusController/WriteProtect
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadAck
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Read
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadAddressMatch
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadAddressProt
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteAddrMatch
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteAddressProt
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteAddress
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteStrobe
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Activation
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/SwBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WTransPulseControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/Operation
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/HwBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferAWVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferAWADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferAWPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferAWREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWSTRB
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferBREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferBVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferBRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferARVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferARADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferARPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferARREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferRREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferRVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferRDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferRRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferReadState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWriteState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/CellBufferWriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadRespCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreWriteRespCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadDataControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadAckControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreWriteAckControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreMatchWriteControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteDiffControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadDiffControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WRegActivation
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadDataStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadAckStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreWriteAckStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/WriteDiffStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/ReadDiffStatusReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadDataCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreReadAckCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreWriteAckCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreMatchReadCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_SpiControllerIfcAxi4Lite/i_SpiControllerBlk_SpiControllerIfc/PreMatchWriteCellBuffer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/SClk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/MiSo
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/MoSi
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/DoTransceivePulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/ReleaseTxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/StoreRxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/TxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/RxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/CPol
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/CPha
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/SClkPeriodInNs
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/TranceiveCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/StretchCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/TxShiftReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_Phy/RxShiftReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/Activation
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/SwBufferPrepared
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/WTransPulseControlReg
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/Operation
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferAvailable
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/SelectedBufferNumberOwnedBySw
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferWriteEnable
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferWriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/CPol
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/CPha
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/SClkPeriodInNs
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/DoTransceivePulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ReleaseTxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/StoreRxDataPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/TxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/RxByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/nCs
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/State
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/CmdId
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ReadHwBufferAddressPointer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ReadHwBufferRepeatAddressPointer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/WriteHwBufferAddressPointer
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ReceiveFrameStartAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/PacketMultiplier
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/PacketLength
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/PacketCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ByteCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ReceiveByteCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/StoreReceiveByte
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ResetReceiveByteCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/WaitNs
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/StartTimerPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/TimerCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/TimerExpired
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/CmdGotoAddressToGoto
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/ForLoopCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/LoopCount
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/CmdEndAddressToGoto
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/AutoRestart
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/SwBuffersPending
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/HwBufferProcessedPulse
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_CmdProcessor/Tranceive
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/SelectedBufferNumberOwnedBySw
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/HwBufferWriteEnable
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/HwBufferAddress
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/HwBufferWriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/HwBufferReadData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/SwBufferWriteEnable
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/SwBufferAddress
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/SwBufferWriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/SwBufferReadData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferWriteEnable0
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferAddress0
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferWriteData0
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferReadData0
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferWriteEnable1
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferAddress1
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferWriteData1
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/BufferReadData1
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/Clk
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/WriteEnable
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/Address
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/WriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/ReadData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i0_Ram/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/Clk
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/WriteEnable
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/Address
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/WriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/ReadData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_DoubleBuffer/i1_Ram/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Rst
add wave -noupdate -expand /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Axi4LiteDown
add wave -noupdate -expand /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Axi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Axi4LiteAccess
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Trace
add wave -noupdate -childformat {{/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.DataWritten -radix hexadecimal} {/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.RamAddress -radix hexadecimal} {/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.RamByteSelect -radix hexadecimal}} -expand -subitemconfig {/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.DataWritten {-height 26 -radix hexadecimal} /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.RamAddress {-height 26 -radix hexadecimal} /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown.RamByteSelect {-height 26 -radix hexadecimal}} /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkDown
add wave -noupdate -childformat {{/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkUp.DataToBeRead -radix hexadecimal}} -expand -subitemconfig {/tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkUp.DataToBeRead {-height 26 -radix hexadecimal}} /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/PreAxi4LiteUp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/PreAxi4LiteAccess
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/UnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/TimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Read
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadAddressMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteAddrMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/WriteStrobe
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkWriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkWriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/RamBlkWriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/AWVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/AWADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/AWPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/AWREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WSTRB
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/BREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/BVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/BRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ARVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ARADDR
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ARPROT
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ARREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/RREADY
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/RVALID
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/RDATA
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/RRESP
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WritePrivileged
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteSecure
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteInstruction
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadPrivileged
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadSecure
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadInstruction
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Read
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadAddressMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteAddrMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteStrobe
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/UnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/TimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Axi4LiteReadState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/Axi4LiteWriteState
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadTimeoutCounter
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteTimeoutCounter
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadUnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteUnoccupiedAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadTimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteTimeoutAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/ReadProtect
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamIfcAxi4LiteBusController/WriteProtect
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/Clk
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/Rst
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/Read
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadAddressMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadAddressProt
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteAck
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteResp
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/Write
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteAddrMatch
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteAddressProt
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteAddress
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteData
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteStrobe
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/DataToBeRead
add wave -noupdate -radix hexadecimal /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/DataWritten
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/RTransPulseRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WRegPulseRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ExtReadAckRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ExtWriteAckRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/RamAddress
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/RamByteSelect
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreReadData
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreReadDataRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreReadAckRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreWriteAckRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreMatchReadRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/PreMatchWriteRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteDiffRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadDiffRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/DelWriteDiffRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/ReadDecRam
add wave -noupdate -expand /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WriteDecRam
add wave -noupdate /tb_top_axi4lite/i_SpiControllerWithAxi4LiteBus/i_RamIfcAxi4Lite/i_RamBlk_RamIfc/WRegDataWritten
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {333731242 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 1168
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {315209691 ps} {470962648 ps}
